### ISSUE TITLE
Up to date packages tracking for the download webpage

### ISSUE THREAD

**Issue by nado** [supertuxkart/stk-code#2353]
* [X] Debian unstable
* [X] Ubuntu in our ppa
* [X] Archlinux in community repo
* [X] openSuse in TumbleWeed
* [X] Fedora 24, 25, and Rawhide
* [ ] Gentoo 0.9.1, 0.9.2 coming [here](https://github.com/hasufell/games-overlay/tree/master/games-action/supertuxkart)
* [ ] Manjaro: 0.8.2
* [ ] Mageia 0.9.1

Issue to keep track of version changes in distributions packages on this page : https://supertuxkart.net/Download

Feel free to add more un-updated links.

**Comment by MTres19** [comment]
I think I've got everything up-to-date on the wiki. This can probably be closed.

**Comment by qwertychouskie** [comment]
Maybe you can also add the new AppImage, see https://github.com/supertuxkart/stk-code/issues/2448

**Comment by MTres19** [comment]
We've discussed this on IRC; it was decided that it wasn't worth the effort to support AppImage since the regular builds work fine already. I also don't have the permissions to upload the AppImage to SourceForge or the VPS. I suggest you discuss this with the team if you want it.

**Comment by qwertychouskie** [comment]
Also, the mirror link is broken.

**Comment by nado** [comment]
@MTres19 I dont know who handles the wiki anymore, but the gentoo link is incorrect, 0.9.2 is not yet in official overlay, but on the games-overlay from hasufell.

**Comment by qwertychouskie** [comment]
@MTres19 I think you forgot to actually change the link for Gentoo. :)

**Comment by MTres19** [comment]
Could someone post the link please?

**Comment by nado** [comment]
https://github.com/hasufell/games-overlay/tree/master/games-action/supertuxkart

**Comment by MTres19** [comment]
Sorry about that. It's fixed now.

**Comment by probonopd** [comment]
It would be nice to have download links for the AppImage on https://github.com/supertuxkart/stk-code/releases
