### ISSUE TITLE
Issues sorting (wip)

### ISSUE THREAD

**Issue by nado** [supertuxkart/stk-code#2641]
Hi,

This is a wip list of suggestion concerning the visibility and sorting of issues.

## Can be closed

* [ ] #621

## Milestones

* [ ] Move to any milestone
    * [ ] #605
    * [ ] #844
    * [ ] #845
    * [ ] #859
* [ ] Move to "later" or label waiting_for_feedback/testing if no post for a long time
    * [ ] #71 
    * [ ] #569
    * [ ] #574
    * [ ] #788 its been 2 years with consecutive postponing
    * [ ] #798
    * [ ] #829 
    * [ ] #2363
* [ ] Close or move to "later"
    * [ ] #602

### Suggestions

Move "can_not_reproduce" from milestones to labels

## Labels

* [ ] #2363 could get C:3D Modelling

### Suggestions

* [ ] Create a C:controllers or C:controls
    * [ ] #71 
    * [ ] #574
    * [ ] #740
    * [ ] #798
    * [ ] #2240
    * [ ] #2557
    * [ ] #2617

**Comment by nado** [comment]
This was done with helping intentions in mind but I’m closing it because it doesnt seem to help at all in the actual workflow. Better close what’s useless :)
